
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGE = 'CHANGE';
export const DELETE_KUTSU_REQUEST = 'DELETE_KUTSU_REQUEST';
export const DELETE_KUTSU_SUCCESS = 'DELETE_KUTSU_SUCCESS';
export const DELETE_KUTSU_FAILURE = 'DELETE_KUTSU_FAILURE';
export const FETCH_KUTSU_REQUEST = 'FETCH_KUTSU_REQUEST';
export const FETCH_KUTSU_SUCCESS = 'FETCH_KUTSU_SUCCESS';
export const FETCH_KUTSU_FAILURE = 'FETCH_KUTSU_FAILURE';

export const FETCH_FRONTPROPERTIES_REQUEST = 'FETCH_FRONTPROPERTIES_REQUEST';
export const FETCH_FRONTPROPERTIES_SUCCESS = 'FETCH_FRONTPROPERTIES_SUCCESS';
export const FETCH_FRONTPROPERTIES_FAILURE = 'FETCH_FRONTPROPERTIES_FAILURE';
