sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
  - postgresql
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "aeK+dTSf7RIT23QD/Mfqyoz3WWpFfcIWKC2uX2YHCPFNX+t0+8I018POg7NEh89soWY2cQGBzaPtqMakXOPd2FOdhPk7wI2KCML8LvbQIJPStdnhQt+B+v96vQ5yV46mcTbeTFNgRZ7Jm7vfHrZqVAENMjskQoBsgcv2JIiSuu/aZGPIIYMcgL8I4wrF8NakuEm8Do9g6eObtOWQqlr8VDPb+v8uAuZpVA81Gvt18O0mZ7WyxhfBReK4ra64cHq/ABePpbvd2wkW3uFeVv9bg05QHkKdOFik7ZU5jDCALX/3e4gL/ppyyfVvVXY8N3AIkbHa9MHEN3kkHy822/1T/pp1KBCGXJ/7E1euCEIOZiT+Oyaz8e9/pnfqF5h/+f/iQp6Wqt4TRGpJNhM0WW5Wxxbnj4OKD0T4is7J9uyvMEd9mXgCAn5xODiggBmFqLS4SmJFa0SX0dKNulRV/FsHevestrhfFGE7Se4eUPvTDu21PZf/OOVpMy8zSdOdw1tg6axX8+fHF2EABZPpmrkNaJ5iPo6lNT7+GNkZiVti6XP/EQ0twc2J0d3YyT8l+y5M9RYZKxJv6B73xJso6xncVvhb+n8vzzHpDcrgkhq7YYtJ1gbEGoiVKQbehrmO58VW4j5nE6wr6jVV4xLkV/mz6sHhiZ2DIZdlTxWvVl7sEOk="
    # ARTIFACTORY_PASSWORD
    - secure: "U+ALv0HZAmxRmYy+lib0Vxko2em//Hh+i4OMbkF8DzKAzcnACEgKUZLkrjGfS48YQoVaTNjL726rWhjXbe0irp6e47rtdXdwFQGC3FuXWRDel4epfvV5iRCUNT9TezOg8JNaJuxLw+lHZ+NKakkrk+/3ioQugHaqhKMxhXDe5zfgi8OPQDe+wLXfWe/W2e8k63B8bmx16FcbFypWHiikklfvTAd9sOEgSWX2h8Qnj+fiIBW7BUmwn15+UR7j7MRGKU9dGOqXtNR9rMEeFGxB4P+uJ/GbMyNc5BITqX2cFnEH3kAZRra2SPTRpJ7rRCgvs5QVyF/uXYRqVTZiNpT562SRiBrX+6pXaOdIvcVUKkIO1TAbMplaTmm3/1u3AX4AOMLZQWR0hbEI151OmqGsnvbXzPId7dZ8mtrQufLfT8rbpJMboaBQ0r6E++Q93K0i3X2a+hCm9MoAujbUSvXxwTFzGKBlL9TSdryrP75pt+bwEWqhNdrWxb8WihrabZayvsFgdr40VE4xZ45jC9JN8povcKmOD1exqjzOhEf2SUMdKwaXygtwDwwLw9CPYqQ5KXfMmk0TwW0gkpB3KBQtRoXWZ6K+90ukFpXRuvukTmQFrThZg1ckuoPYKHw2pIO0f6N4O7lefkVHW8p/40zofGjD7pGfzWPYyb9o4Mvw+v4="
    # AWS_ACCESS_KEY_ID
    - secure: "FCVkrSPKebCr2buJjzxdOyaOcDhUCjeYv1uAR5UXYJAz2RShNPOEoj3GAYuuhU9B9UXG4T3ampofzlUreEwQ2U6RfDzp/eKVKkwFOka3aeQGZvC7ID1jBjE/liFbEnByZ46DR/svxOWpNWoWxw7sQQNalgBYrOiS0cz2m2ubdkahzYMI6V+726cgIJAzJm8Pvu5F2Zy/KYus3rd5O/0K9kcFskuet30pYOMytd3TNqJXlF5l3b/jWaRAk+pZhTnHLYi8P8AsBVeAItDNReNBykgQNSvBbI49k8fDI6RUF519yvZS0gw3mnyGNOpAOqnxm39QNEwNOdBtCy0N+TLpJ5Urayk8yDpPi+iyqdzBZJ1cz+s8pO06gR5P+EuIGl/sx17yrIu2zzTb90V8jXyqLfCajMzW0QXlTsTQJUsJNGKBQV/mNPKTUaq+cW+B4IjP7XCbyfxPHzEUeTiswYm1Wf/jroAudy5dcdqHviD32lxYfe37+RHAyYeSgg+NHsSUmN322p/xqfUZrdlMqs5UyagIWx8sU7A2SgGlmkm5rH9DsARc1W+mPWz5DC70LjUu/l2w9NV30JuyvohYRjgcO8FeMOpO3xtLEOjnWp9eypoRjwzniPlIKFxdxME4lJXLpifabz9GnmTxBGOrB2tPJPrT1PjIA66p+5PcTRJV4xc="
    # AWS_SECRET_ACCESS_KEY
    - secure: "KvENbgNoQPItDdtvfOqFZpyCVIi0I/1HXLIr8b/96r+gmwMt1jRk4W7U3SL/XjymBUX9CLI0TGcVKLrLjK0O7KXEdTf4gK3YipFnWfsF/5dJ21qdYZmDSG3KVYARZc1hUWF1fq1xkHYczBbUnHb7R4jrhrtChb68oVjyd9Za/AzUYp/SgrA6elMDQqqKV9r7xjSHsqJnBpXNuYEYRGQ9SoUVHLfPncQwPvwTfH0avIqQMA06QXnjUQ4OBsFLbWIa1qAQPG1HeWjzpKbgyXIYnFE6Pna6v7mpEZWamxIo7GoKPmRVmw7jvio9v2/YXLglg2i/veqQOTpL/y10LC4HOu4Qjr3ThyNvhIIAK4GX+DUU8t2x+oQyYlSNjvnvbNwilWaRDZ7ARK9FTxKnyWUB9qIerLNYC9w2VnbKAvghulbvA5nAV1iJf3H6gjYxXwti0kLeA/Fznpq6FN7BxBo4b+0wI1m7xsbLucRo6y40/zIMV3srAVhqfFgHX3MYgdUjxGHlS03gGhDMJ9ng+yWTQAWghZYo3j1usuyFG2gklbR+DL1O0ejNegcKImhR43gRzz8oK2n8JRxhFWL2B6q9h89YbuP6DFoV0VItjSfrdAdhOZyLEfOGHyTwBy7M8UI4qbFH/ZkT6hbNIoMLO40IBdvGe7Q8pD4o/RZxTsBEMj8="

addons:
  sonarcloud:
    organization: "opetushallitus"
    token:
      secure: "KPY8I7ehWkNQZifDguUVneWfHredC4QkW7Uy1L/azeniNIu7Q9U/1O9TBczpnDWVnZ1F1yFsVp/nsuW/IpON5hUdRY/YlrF38xC+QIAHvkMgoOIQ3BkNVFSHC88k7BmWSqZ9Izuqojega3Tz5wROZ4pta2voi4k60aYshwiC88qu4BS2EjZ3FWDDx1ZrOf9tpRDMXBIwRTKPi/HfsCSNEOr/fVe/MpkhJcibou8vOa20UMTsMf2OhJNuGbBT8XmkbhyFktk5SUh0NFBQUCi7nQGkbxl4UCOeGBeN3n3FiHU/uAbzMbN5M5jGp1Hn+kgqPK39SF6QxzSBmYWSTF4wJU2GgRaZNWXap87BoGI6yLdtIZuj/t846aR9pQaPnsQCiMi8+G6vu4kz3vgEG4hLPWbNxX3GDJxgu+qREpwTP+w0kGxbK8dm0+D6OiHi0LGbLXEAjShBgI73odmoIKsi3p1ePjN9hEbiWweBj8Cq8C92JjcEc2EU8XFiazJfwnQ+IB5TZ1CqX69V751FoF1cmeuCG42QMyPP5D7krkzeKmQtBTiemKSeOk2MdwY83NyPbBVw9kCl2Wlde/o2ySqu3IzBR9F2Zr3aUoRZUZOIx7nEpWf0bE+EuCfv9UYs7ZFFUcstMxUHIeg/NLddXnKB2HQlFdS8laBiDcb0gqsE/HA="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="oppijanumerorekisteri"

before_script:
  - psql -c "CREATE USER \"oph\" PASSWORD 'oph';" -U postgres
  - psql -c "CREATE DATABASE \"oppijanumerorekisteri\" OWNER 'oph';" -U postgres
  # regrettably, migrations require extensive rights:
  - psql -c "ALTER ROLE \"oph\" WITH superuser;" -U postgres

script:
  - mvn -P ci clean install sonar:sonar -Dsonar.projectKey=Opetushallitus_oppijanumerorekisteri -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv oppijanumerorekisteri-service/target/oppijanumerorekisteri-service-*SNAPSHOT.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: mvn deploy -pl oppijanumerorekisteri-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
