services:
  database:
    container_name: oph-oppijanumerorekisteri-db
    image: postgres:16.14@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5434:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-database:
    container_name: oph-oppijanumerorekisteri-test-db
    image: postgres:16.14@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5435:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.31.0-alpine@sha256:2f07d83bf561b506400dc183b1b2003803e39efbd22451f848adaba14d28c7c7
    ports:
      - 8080:8080
    volumes:
      - ./henkilo-ui/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  database-data:
