services:
  database:
    container_name: oph-oppijanumerorekisteri-db
    image: postgres:16.13@sha256:5a65324fe84dc41709ff914e90b07f3e2f577073ed27bf917d4873aca0c9ec51
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5434:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-database:
    container_name: oph-oppijanumerorekisteri-test-db
    image: postgres:16.13@sha256:5a65324fe84dc41709ff914e90b07f3e2f577073ed27bf917d4873aca0c9ec51
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5435:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.30.0-alpine@sha256:0272e4604ed93c1792f03695a033a6e8546840f86e0de20a884bb17d2c924883
    ports:
      - 8080:8080
    volumes:
      - ./henkilo-ui/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  database-data:
