services:
  database:
    container_name: oph-oppijanumerorekisteri-db
    image: postgres:16.15@sha256:65b16a8b326e0cfbdf33fa7e783f2a0cb352a61448616ccccfd616ef42aa0f65
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5434:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-database:
    container_name: oph-oppijanumerorekisteri-test-db
    image: postgres:16.15@sha256:65b16a8b326e0cfbdf33fa7e783f2a0cb352a61448616ccccfd616ef42aa0f65
    environment:
      - POSTGRES_USER=oph
      - POSTGRES_DB=oppijanumerorekisteri
      - POSTGRES_PASSWORD=oph
    ports:
      - 5435:5432
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oph -d oppijanumerorekisteri"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    # docker host can be reached from inside the container with this host name. WSL and Linux need this, MacOS does not.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: nginx:1.31.6-alpine@sha256:df221db836e1754089190208cee7eeda94f233197056426eda74a43ab1abeac2
    ports:
      - 8080:8080
    volumes:
      - ./henkilo-ui/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  database-data:
