cas.url: https://virkailija.untuvaopintopolku.fi/cas
cas.login: https://virkailija.untuvaopintopolku.fi/cas/login
henkiloui.url: https://virkailija.untuvaopintopolku.fi/henkilo-ui
henkiloui.uses-ssl-proxy: true