cas.url: https://virkailija.testiopintopolku.fi/cas
cas.login: https://virkailija.testiopintopolku.fi/cas/login
henkiloui.url: https://virkailija.testiopintopolku.fi/henkilo-ui
henkiloui.uses-ssl-proxy: true
