COMMENT ON COLUMN asiayhteys_hakemus.hakemus_oid IS 'Ei vielä käytössä.';
COMMENT ON COLUMN asiayhteys_kayttooikeus.henkilo_id IS 'Ei vielä käytössä.';
COMMENT ON COLUMN asiayhteys_palvelu.henkilo_id IS 'Ei vielä käytössä.';
COMMENT ON COLUMN cas_client_session.mapping_id IS 'Tekninen.';
COMMENT ON COLUMN externalid.externalid IS 'Tekninen.';
COMMENT ON COLUMN henkilo.aidinkieli_id IS 'Henkilön äidinkieli. Syntyy VTJ:stä hetullisille, Koodisto: kieli.';
COMMENT ON COLUMN henkilo.asiointikieli_id IS 'Asiointikieli, ei tule VTJ:n tietojen perusteella, Koodisto: kieli.';
COMMENT ON COLUMN henkilo.created IS 'Luontipäivä.';
COMMENT ON COLUMN henkilo.duplicate IS 'Onko tämä henkilö jonkun toisen henkilön duplikaatti. (Joku toinen on master)';
COMMENT ON COLUMN henkilo.eisuomalaistahetua IS 'Onko henkilöllä suomalaista hetua. Käytetään suoritusrekisterissä.';
COMMENT ON COLUMN henkilo.etunimet IS 'Henkilön etunimet.';
COMMENT ON COLUMN henkilo.hetu IS 'Henkilön hetu.';
COMMENT ON COLUMN henkilo.id IS 'Sisäinen tietokantaid henkilölle.';
COMMENT ON COLUMN henkilo.kasittelija IS 'Viimeksi muokanneen virkailijan oid. Järjestelmän tekemissä muutoksissa käsittelijä pysyy samana.';
COMMENT ON COLUMN henkilo.kotikunta IS 'Koodisto:kunta.';
COMMENT ON COLUMN henkilo.kuolinpaiva IS 'VTJ:stä saatava tieto kuolinpäivästä.';
COMMENT ON COLUMN henkilo.kutsumanimi IS 'Henkilön haluama kutsumanimi, kutsumanimen tulee olla yksi henkilön etunimistä. ';
COMMENT ON COLUMN henkilo.modified IS 'Viimeisin muokkausaika.';
COMMENT ON COLUMN henkilo.oidhenkilo IS 'Henkilön uniikki oid tunniste.';
COMMENT ON COLUMN henkilo.passivoitu IS 'Henkilöä ei poisteta koskaan, se passivoidaan.';
COMMENT ON COLUMN henkilo.sukunimi IS 'Henkilön sukunimi.';
COMMENT ON COLUMN henkilo.sukupuoli IS 'Koodisto:sukupuoli.';
COMMENT ON COLUMN henkilo.syntymaaika IS 'Henkilön syntymäaika.';
COMMENT ON COLUMN henkilo.turvakielto IS 'VTJ:stä saatava tieto onko turvakieltoa.';
COMMENT ON COLUMN henkilo.version IS 'Optimistinen lukitus, kaksi transaktiota ei voi päivittää jos data on muuttunut.';
COMMENT ON COLUMN henkilo.vtj_register IS 'Onko henkilö mukana VTJ synkronoinnissa.';
COMMENT ON COLUMN henkilo.vtjsync_timestamp IS 'Viimeisimmän henkilön tietojen VTJ synkronoinnin timestamp.';
COMMENT ON COLUMN henkilo.yksilointi_yritetty IS 'Onko automaattista yksilöintiä yritetty. Käytetään asynkronisessa VTJ käsittelijässä.';
COMMENT ON COLUMN henkilo.yksiloity IS 'Onko oppija yksilöity (hetuttomille, manuaalinen).';
COMMENT ON COLUMN henkilo.yksiloityvtj IS 'Onko oppija yksilöity (hetullisille, automaattinen).';
COMMENT ON COLUMN henkilo_hetu.henkilo_id IS 'Viittaustaulu, Henkilön kaikki viralliset hetut (nykyinen ja joskus käytössä olleet). Ei sisällä yksilöimättömien henkilöiden hetuja.';
COMMENT ON COLUMN henkilo_hetu.hetu IS 'Henkilön hetu.';
COMMENT ON COLUMN henkilo_huoltaja_suhde.huoltaja_id IS 'Huoltajan henkilötaulun tietokantaid.';
COMMENT ON COLUMN henkilo_huoltaja_suhde.huoltajuustyyppi_koodi IS 'Koodisto:huoltajuustyyppi.';
COMMENT ON COLUMN henkilo_huoltaja_suhde.id IS 'Henkilöhuoltajasuhteen tietokantaid.';
COMMENT ON COLUMN henkilo_huoltaja_suhde.lapsi_id IS 'Lapsen henkilötaulun tietokantaid.';
COMMENT ON COLUMN henkilo_huoltaja_suhde.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN henkilo_kansalaisuus.henkilo_id IS 'Viittaustaulu, yhdellä henkilöllä voi olla monta kansalaisuutta.';
COMMENT ON COLUMN henkilo_kansalaisuus.kansalaisuus_id IS 'Koodisto: maatjavaltiot2, henkilön kansalaisuustaulun kantaid.';
COMMENT ON COLUMN henkilo_kielisyys.henkilo_id IS 'Viittaustaulu, yhdellä henkilöllä voi olla useampi äidinkieli ja asiointikieli.';
COMMENT ON COLUMN henkilo_kielisyys.kielisyys_id IS 'Kielisyyden kantaid.';
COMMENT ON COLUMN henkilo_organisaatio.henkilo_id IS 'Viittaustaulu. Oppijan organisaatiot (oppijan tuonti ja muutospalvelu).';
COMMENT ON COLUMN henkilo_organisaatio.organisaatio_id IS 'Oppijan organisaation kantaid.';
COMMENT ON COLUMN henkilo_passinumero.henkilo_id IS 'Viittaustaulu. Henkilön passinumero.';
COMMENT ON COLUMN henkilo_passinumero.passinumero IS 'Henkilön passinumero. Syntyy hakemukselta.';
COMMENT ON COLUMN henkiloviite.id IS 'Henkilön duplikaattihaun henkilöviitteet.';
COMMENT ON COLUMN henkiloviite.master_oid IS 'Omistavan henkilön oid.';
COMMENT ON COLUMN henkiloviite.slave_oid IS 'Omistavan henkilön mahdollisen duplikaattihenkilön oid.';
COMMENT ON COLUMN henkiloviite.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN kansalaisuus.id IS 'Henkilön kansalaisuudet.';
COMMENT ON COLUMN kansalaisuus.kansalaisuuskoodi IS 'Yksittäinen kansalaisuuskoodi.';
COMMENT ON COLUMN kansalaisuus.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN kielisyys.id IS 'Kansalaisuuden tietokantaid.';
COMMENT ON COLUMN kielisyys.kielikoodi IS 'Kansalaisuuden kielen koodi, Koodisto: kieli.';
COMMENT ON COLUMN kielisyys.kielityyppi IS 'Kansalaisuuden kielen tyyppi.';
COMMENT ON COLUMN kielisyys.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN organisaatio.id IS 'Organisaation tietokantaid.';
COMMENT ON COLUMN organisaatio.oid IS 'Oppijan organisaatio oid, haun tehostamiseksi.';
COMMENT ON COLUMN organisaatio.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN revinfo.rev IS 'Tekninen. Taulujen automaattiauditointiin liittyvä.';
COMMENT ON COLUMN scheduled_tasks.consecutive_failures IS 'Tekninen. Ajastettujen taskien tiedot.';
COMMENT ON COLUMN schema_table_onr.checksum IS 'Tekninen. Flyway tietokantamigraatioiden taulu.';
COMMENT ON COLUMN spring_session.creation_time IS 'Tekninen. Palvelun sessioiden tiedot.';
COMMENT ON COLUMN spring_session_attributes.attribute_bytes IS 'Tekninen. Palvelun sessioiden tiedot.';
COMMENT ON COLUMN tuonti.data_id IS 'Oppijan tuonnin dataa.';
COMMENT ON COLUMN tuonti_organisaatio.organisaatio_id IS 'Oppijan tuonnin dataa.';
COMMENT ON COLUMN tuonti_rivi.henkilo_id IS 'Oppijan tuonnin dataa.';
COMMENT ON COLUMN yhteystiedot.id IS 'Yhteistiedon tietokantaid.';
COMMENT ON COLUMN yhteystiedot.version IS 'Tekninen. Optimistinen lukitus.';
COMMENT ON COLUMN yhteystiedot.yhteystiedotryhma_id IS 'Tekninen. Viittaus.';
COMMENT ON COLUMN yhteystiedot.yhteystieto_arvo IS 'Yhteystieto.';
COMMENT ON COLUMN yhteystiedot.yhteystieto_tyyppi IS 'Enumeraatio, mikä yhteystietotyyppi on kyseessä. YHTEYSTIETO_SAHKOPOSTI, PUHELINNUMERO, MATKAPUHELINNUMERO, KATUOSOITE, KUNTA, POSTINUMERO, KAUPUNKI, MAA.';
COMMENT ON COLUMN yhteystiedotryhma.henkilo_id IS 'Henkilön tietokantaid.';
COMMENT ON COLUMN yhteystiedotryhma.id IS 'Yhteistietoryhmän tietokantaid.';
COMMENT ON COLUMN yhteystiedotryhma.read_only IS 'Saako yhteystietoa päivittää. (VTJ yhteystiedot ovat lukitut).';
COMMENT ON COLUMN yhteystiedotryhma.ryhma_alkuperatieto IS 'Koodisto: yhteystietojenalkupera.';
COMMENT ON COLUMN yhteystiedotryhma.ryhmakuvaus IS 'Koodisto: yhteystietotyypit.';
COMMENT ON COLUMN yhteystiedotryhma.version IS 'Tekninen. Optimistinen lukitus.';
COMMENT ON COLUMN yksilointitieto.aidinkieli_id IS 'Henkilön yksilöintitiedot VTJ:stä tai manuaalisesti luotuna joilla voidaan korvata henkilön perustiedot.';
COMMENT ON COLUMN yksilointitieto.etunimet IS 'Henkilön etunimet.';
COMMENT ON COLUMN yksilointitieto.henkiloid IS 'Henkilön uniikki oid tunniste.';
COMMENT ON COLUMN yksilointitieto.hetu IS 'Henkilön hetu.';
COMMENT ON COLUMN yksilointitieto.id IS 'Tekninen, yksilöintitiedon tietokantaid.';
COMMENT ON COLUMN yksilointitieto.kotikunta IS 'Henkilön kotikunta.';
COMMENT ON COLUMN yksilointitieto.kutsumanimi IS 'Henkilön kutsumanimi.';
COMMENT ON COLUMN yksilointitieto.sukunimi IS 'Henkilön sukunimi.';
COMMENT ON COLUMN yksilointitieto.sukupuoli IS 'Henkilön sukupuoli.';
COMMENT ON COLUMN yksilointitieto.turvakielto IS 'Onko henkilö asetettu turvakieltoon.';
COMMENT ON COLUMN yksilointitieto.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN yksilointivirhe.aikaleima IS 'Yksilöinnissä tapahtuneen virheen aikaleima.';
COMMENT ON COLUMN yksilointivirhe.henkilo_id IS 'Viittaus henkilöön jonka yksilöintiä virhe koskee.';
COMMENT ON COLUMN yksilointivirhe.id IS 'Yksilöintivirheen tietokantaid.';
COMMENT ON COLUMN yksilointivirhe.poikkeus IS 'Yksilöintivirheen luomiseen johtanut tarkempi tekninen poikkeus.';
COMMENT ON COLUMN yksilointivirhe.uudelleenyritys_aikaleima IS 'Viimeisimmän yksilöinnin uudelleen yrityksen aikaleima.';
COMMENT ON COLUMN yksilointivirhe.uudelleenyritys_maara IS 'Kuinka monta kertaa yksilöinti on yritetty uudelleen.';
COMMENT ON COLUMN yksilointivirhe.version IS 'Tekninen, optimistinen lukitus.';
COMMENT ON COLUMN yksilointivirhe.viesti IS 'Yksilöintivirheen selite.';
