spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  cache:
    type: EHCACHE
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    org.hibernate.SQL: error
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error
