server:
  servlet:
    context-path: /oppijanumerorekisteri-service
    session:
      cookie:
        name: JSESSIONID
  port: 8080
spring:
  main:
    banner-mode: "off"
    allow-circular-references: true # HuoltajaCreateDtoMapper
  session:
    store-type: jdbc
  jackson:
    serialization:
      write-dates-as-timestamps: true
  cache:
    type: EHCACHE
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oppijanumerorekisteri?ApplicationName=oppijanumerorekisteri-service
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
      connection-timeout: 10000
      max-lifetime: 900000
  flyway:
    enabled: true
    table: schema_table_onr
    # Only for initial production release, set false afterwards
    baseline-on-migrate: false
    # If DB is not empty will not run migrations until this version
    baseline-version: 20180423104403142
    out-of-order: true
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
      use-new-id-generator-mappings: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.integration.envers.enabled: true
      # https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true
      org.hibernate.envers.store_data_at_delete: true
management:
  health:
    diskspace:
      enabled: false
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    org.hibernate.SQL: error
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error
    io.swagger.models.parameters.AbstractSerializableParameter: error
    fi.vm.sade.oppijanumerorekisteri.aspects.LogExecutionTimeAspect: debug
dev:
  username: user
  password: password
cas:
  service: http://localhost:${server.port}/oppijanumerorekisteri-service
  send-renew: false
  key: oppijanumerorekisteri-service
host:
  host-virkailija: localhost:${server.port}
  host-cas: localhost:${server.port}
  host-alb: http://localhost:${server.port}
authentication:
  default:
    username: oppijanumerorekisteri
    password: oppijanumerorekisteri
  kayttooikeus:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
  vtj:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
  hakuapp:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
  ataru:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
  henkilotietomuutos:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
  viestintapalvelu:
    username: ${authentication.default.username}
    password: ${authentication.default.password}
oppijanumerorekisteri:
  uses-ssl-proxy: false
  disable-same-site-cookie: false
  scheduling:
    vtjsync:
      asiayhteysKaytossa: false
  allow-fake-ssn: true
aws:
  region: eu-west-1
  henkiloModifiedTopic:
    enabled: false
    topicArn: disabled