server:
  servlet:
    context-path: /oppijanumerorekisteri-service
    session:
      cookie:
        name: JSESSIONID
spring:
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
  jackson:
    serialization:
      write-dates-as-timestamps: true
  cache:
    type: EHCACHE
  flyway:
    enabled: true
    table: schema_table_onr
    # Only for initial production release, set false afterwards
    baseline-on-migrate: false
    # If DB is not empty will not run migrations until this version
    baseline-version: 20180423104403142
    out-of-order: true
logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    org.hibernate.SQL: error
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error
