ALTER TABLE tiedote ALTER COLUMN url DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN otsikko_fi DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN otsikko_sv DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN otsikko_en DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN viesti_fi DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN viesti_sv DROP NOT NULL;
ALTER TABLE tiedote ALTER COLUMN viesti_en DROP NOT NULL;
