spring.security.oauth2.resourceserver.jwt.issuer-uri: https://dev.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://dev.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.henkilo.solmuluokka: 198

oppijanumerorekisteri.vtj-muutosrajapinta.fetch-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.muutostieto-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.perustieto-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.base-url: https://proxy.dev.palveluvayla.opintopolku.fi
oppijanumerorekisteri.vtj-muutosrajapinta.palveluvayla-env: FI-DEV

oppijanumerorekisteri.vtjkysely.enabled: false
oppijanumerorekisteri.vtjkysely.address: http://alb.untuvaopintopolku.fi/vtj-test-ws/ws/
oppijanumerorekisteri.vtjkysely.keystoreUri: /root/oph-environment/authentication/vtj-service/keystore.p12
oppijanumerorekisteri.vtjkysely.certAlias: vtj-service
oppijanumerorekisteri.vtjkysely.truststoreUri: /root/oph-environment/authentication/vtj-service/truststore.p12

viestinvalitys.baseurl: https://viestinvalitys.untuvaopintopolku.fi/lahetys

oppijanumerorekisteri.scheduling.yksilointi.enabled: false
oppijanumerorekisteri.allow-fake-ssn: true
