spring.security.oauth2.resourceserver.jwt.issuer-uri: https://virkailija.hahtuvaopintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://virkailija.hahtuvaopintopolku.fi/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.tasks.export.enabled: true
oppijanumerorekisteri.tasks.export.bucket-name: ${export_bucket_name}
oppijanumerorekisteri.tasks.export.copy-to-lampi: false
oppijanumerorekisteri.tasks.export.lampi-bucket-name: none
oppijanumerorekisteri.tasks.export.lampi-role-arn: none
oppijanumerorekisteri.tasks.export.lampi-external-id: none

oppijanumerorekisteri.tasks.pseudonymized-export.enabled: true

oppijanumerorekisteri.vtj-muutosrajapinta.fetch-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.muutostieto-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.perustieto-enabled: false

oppijanumerorekisteri.vtjkysely.enabled: false
oppijanumerorekisteri.vtjkysely.address: http://alb.hahtuvaopintopolku.fi/vtj-test-ws/ws/
oppijanumerorekisteri.vtjkysely.keystoreUri: /root/oph-environment/authentication/vtj-service/keystore.p12
oppijanumerorekisteri.vtjkysely.certAlias: vtj-service
oppijanumerorekisteri.vtjkysely.truststoreUri: /root/oph-environment/authentication/vtj-service/truststore.p12