spring.security.oauth2.resourceserver.jwt.issuer-uri: https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.vtjkysely.enabled: false
oppijanumerorekisteri.vtjkysely.address: http://localhost
oppijanumerorekisteri.vtjkysely.keystoreUri: classpath:/dummykeystore.jks
oppijanumerorekisteri.vtjkysely.certAlias: dummyalias
oppijanumerorekisteri.vtjkysely.truststoreUri: classpath:/dummytruststore.jks

oppijanumerorekisteri.scheduling.yksilointi.enabled: false
oppijanumerorekisteri.allow-fake-ssn: true

oppijanumerorekisteri.tasks.testidatantuonti.import.enabled: true
