spring:
  jpa:
    properties:
      hibernate.integration.envers.enabled: ${versiointi_kaytossa:true}
  datasource:
    url: jdbc:postgresql://${postgresql_host}:${postgresql_port}/oppijanumerorekisteri?ApplicationName=oppijanumerorekisteri-service
    username: ${postgresql_username}
    password: ${postgresql_password}
    hikari:
      maximum-pool-size: ${postgresql_maximum_pool_size:20}
      connection-timeout: ${postgresql_connection_timeout:10000}
      max-lifetime: ${postgresql_max_lifetime:900000}
server:
  jetty:
    connection-idle-timeout: ${connection_idle_timeout:30000}
cas:
  service: https://${host_virkailija}/oppijanumerorekisteri-service
host:
  host-virkailija: ${host_virkailija}
  host-cas: ${host_cas}
authentication:
  kayttooikeus:
    username: ${kayttooikeus_username}
    password: '${kayttooikeus_password}'
  hakuapp:
    username: ${authentication_app_username_to_haku}
    password: ${authentication_app_password_to_haku}
  ataru:
    username: ${ataru_username}
    password: ${ataru_password}
  viestintapalvelu:
    username: ${viestinta_username}
    password: ${viestinta_password}

oppijanumerorekisteri:
  uses-ssl-proxy: true
  disable-strict-permission-check: ${disable_strict_permission_check:false}
  slack-url: ${slack_webhook_url}
  scheduling:
    yksilointi:
      enabled: ${yksilointi_enabled:true}
  allow-fake-ssn: ${allow_fake_ssn:true}
  vtj-muutosrajapinta:
    base-url: ${vtjmuutosrajapinta_baseurl}
    username: ${vtjmuutosrajapinta_username}
    password: ${vtjmuutosrajapinta_password}
    palveluvayla-env: ${palveluvayla_env:FI-TEST}
    apigw-role-arn: ${apigw_role_arn}
  oauth2:
    clientId: ${oauth2_clientid}
    clientSecret: ${oauth2_clientsecret}
  vtjkysely:
    username: ${vtjkysely_username}
    password: ${vtjkysely_password}
    keystorePassword: ${vtjkysely_keystore_password}
    truststorePassword: ${vtjkysely_truststore_password}
aws:
  region: ${aws_region}
  henkiloModifiedTopic:
    enabled: ${henkilo_modified_topic_enabled:true}
    topicArn: '${henkilo_modified_sns_topic_arn}'
