spring:
  jpa:
    properties:
      hibernate.integration.envers.enabled: true
  datasource:
    url: jdbc:postgresql://${postgresql_host}:${postgresql_port}/oppijanumerorekisteri?ApplicationName=oppijanumerorekisteri-service
    username: ${postgresql_username}
    password: ${postgresql_password}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      max-lifetime: 900000
cas:
  service: https://${host_virkailija}/oppijanumerorekisteri-service
host:
  host-virkailija: ${host_virkailija}
  host-cas: ${host_cas}
authentication:
  kayttooikeus:
    username: ${kayttooikeus_username}
    password: '${kayttooikeus_password}'
  hakuapp:
    username: ${authentication_app_username_to_haku}
    password: ${authentication_app_password_to_haku}
  ataru:
    username: ${ataru_username}
    password: ${ataru_password}
  viestintapalvelu:
    username: ${viestinta_username}
    password: ${viestinta_password}

oppijanumerorekisteri:
  uses-ssl-proxy: true
  slack-url: ${slack_webhook_url}
  vtj-muutosrajapinta:
    username: ${vtj_muutosrajapinta_username}
    password: ${vtj_muutosrajapinta_password}
    apigw-role-arn: ${palveluvayla_apigw_role_arn}
  oauth2:
    clientId: ${oauth2_clientid}
    clientSecret: ${oauth2_clientsecret}
  vtjkysely:
    username: ${vtjkysely_username}
    password: ${vtjkysely_password}
    keystorePassword: ${vtjkysely_keystore_password}
    truststorePassword: ${vtjkysely_truststore_password}
aws:
  region: ${aws_region}
  opintopolkuRoleArn: ${opintopolku_cross_account_role}
  henkiloModifiedTopic:
    enabled: true
    topicArn: '${henkilo_modified_sns_topic_arn}'