spring.security.oauth2.resourceserver.jwt.issuer-uri: https://${host_virkailija}/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://${host_virkailija}/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.tasks.export.enabled: true
oppijanumerorekisteri.tasks.export.bucket-name: ${export_bucket_name}
oppijanumerorekisteri.tasks.export.copy-to-lampi: true
oppijanumerorekisteri.tasks.export.lampi-bucket-name: oph-lampi-prod
oppijanumerorekisteri.tasks.export.lampi-role-arn: ${lampi_role_arn}
oppijanumerorekisteri.tasks.export.lampi-external-id: ${lampi_external_id}

oppijanumerorekisteri.vtj-muutosrajapinta.fetch-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.muutostieto-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.perustieto-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.base-url: https://proxy.prod.palveluvayla.opintopolku.fi
oppijanumerorekisteri.vtj-muutosrajapinta.palveluvayla-env: FI

oppijanumerorekisteri.vtjkysely.enabled: true
oppijanumerorekisteri.vtjkysely.address: https://vtjkysely.2016.vrk.fi/sosowebsite/soso.asmx
oppijanumerorekisteri.vtjkysely.keystoreUri: /app/vtjkysely-keystore
oppijanumerorekisteri.vtjkysely.certAlias: opintopolku.fi
oppijanumerorekisteri.vtjkysely.truststoreUri: /app/vtjkysely-truststore

viestinvalitys.baseurl: https://viestinvalitys.opintopolku.fi/lahetys

oppijanumerorekisteri.scheduling.yksilointi.enabled: true
oppijanumerorekisteri.allow-fake-ssn: false
