spring.security.oauth2.resourceserver.jwt.issuer-uri: https://kayttooikeus.qa.yleiskayttoiset.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://kayttooikeus.qa.yleiskayttoiset.opintopolku.fi/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.henkilo.solmuluokka: 98

oppijanumerorekisteri.vtj-muutosrajapinta.fetch-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.muutostieto-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.perustieto-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.base-url: https://proxy.qa.palveluvayla.opintopolku.fi
oppijanumerorekisteri.vtj-muutosrajapinta.palveluvayla-env: FI-TEST

oppijanumerorekisteri.vtjkysely.enabled: false
oppijanumerorekisteri.vtjkysely.address: http://alb.testiopintopolku.fi/vtj-test-ws/ws/
oppijanumerorekisteri.vtjkysely.keystoreUri: /root/oph-environment/authentication/vtj-service/keystore.p12
oppijanumerorekisteri.vtjkysely.certAlias: vtj-service
oppijanumerorekisteri.vtjkysely.truststoreUri: /root/oph-environment/authentication/vtj-service/truststore.p12

viestinvalitys.baseurl: https://viestinvalitys.testiopintopolku.fi/lahetys

oppijanumerorekisteri.scheduling.yksilointi.enabled: false
oppijanumerorekisteri.allow-fake-ssn: true
