spring.security.oauth2.resourceserver.jwt.issuer-uri: https://qa.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://qa.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks

oppijanumerorekisteri.henkilo.solmuluokka: 98

oppijanumerorekisteri.vtj-muutosrajapinta.fetch-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.muutostieto-enabled: true
oppijanumerorekisteri.vtj-muutosrajapinta.perustieto-enabled: false
oppijanumerorekisteri.vtj-muutosrajapinta.base-url: https://proxy.qa.palveluvayla.opintopolku.fi
oppijanumerorekisteri.vtj-muutosrajapinta.palveluvayla-env: FI-TEST

oppijanumerorekisteri.vtjkysely.enabled: false
oppijanumerorekisteri.vtjkysely.address: http://alb.testiopintopolku.fi/vtj-test-ws/ws/
oppijanumerorekisteri.vtjkysely.keystoreUri: /root/oph-environment/authentication/vtj-service/keystore.p12
oppijanumerorekisteri.vtjkysely.certAlias: vtj-service
oppijanumerorekisteri.vtjkysely.truststoreUri: /root/oph-environment/authentication/vtj-service/truststore.p12

viestinvalitys.baseurl: https://viestinvalitys.testiopintopolku.fi/lahetys
ataru.baseurl: https://virkailija.testiopintopolku.fi/lomake-editori
haku-app.baseurl: https://virkailija.testiopintopolku.fi/haku-app

oppijanumerorekisteri.scheduling.yksilointi.enabled: false
oppijanumerorekisteri.allow-fake-ssn: true

henkilo-ui.oppijoidentuonti: https://virkailija.testiopintopolku.fi/henkilo-ui/oppijoidentuonti

kayttooikeus-service.henkilo.byOid: https://virkailija.testiopintopolku.fi/kayttooikeus-service/henkilo/{henkiloOid}
kayttooikeus-service.s2s-checkUserPermissionToUser: https://virkailija.testiopintopolku.fi/kayttooikeus-service/s2s/canUserAccessUser
kayttooikeus-service.henkilo-passivoi: https://virkailija.testiopintopolku.fi/kayttooikeus-service/henkilo/{henkiloOid}/passivoi
kayttooikeus-service.henkilo.sallitut: https://virkailija.testiopintopolku.fi/kayttooikeus-service/henkilo/{henkiloOid}/kayttooikeudet

koodisto-service.koodi: https://virkailija.testiopintopolku.fi/koodisto-service/rest/json/{koodistoUri}/koodi

organisaatio-service.organisaatio.byOid: https://virkailija.testiopintopolku.fi/organisaatio-service/rest/organisaatio/{organisaatioOid}
organisaatio-service.organisaatio.byOid.childoids: https://virkailija.testiopintopolku.fi/organisaatio-service/rest/organisaatio/{organisaatioOid}/childoids