oppijanumerorekisteri.tasks.export.enabled: false
oppijanumerorekisteri.tasks.export.bucket-name: oph-yleiskayttoiset-export-untuva
oppijanumerorekisteri.tasks.export.copy-to-lampi: true
oppijanumerorekisteri.tasks.export.lampi-bucket-name: oph-lampi-dev
oppijanumerorekisteri.tasks.export.lampi-role-arn: ${ssm_lampi_role_arn}
oppijanumerorekisteri.tasks.export.lampi-external-id: ${ssm_lampi_external_id}
