oppijanumerorekisteri.tasks.export.enabled: true
oppijanumerorekisteri.tasks.export.bucket-name: oph-yleiskayttoiset-export-untuva
oppijanumerorekisteri.tasks.export.copy-to-lampi: true
oppijanumerorekisteri.tasks.export.lampi-bucket-name: oph-lampi-dev
oppijanumerorekisteri.tasks.export.lampi-role-arn: ${ssm_lampi_role_arn}
oppijanumerorekisteri.tasks.export.lampi-external-id: ${ssm_lampi_external_id}

authentication.vtj-kysely.address: "http://alb.untuvaopintopolku.fi/vtj-test-ws/ws/"
authentication.vtj-kysely.username: ${ssm_vtj_username}
authentication.vtj-kysely.password: ${ssm_vtj_password}
authentication.vtj-kysely.keystore.file: ${ssm_keystore_file}
authentication.vtj-kysely.keystore.password: ${ssm_vtj_keystore_password}
authentication.vtj-kysely.truststore.file: ${ssm_truststore_file}
authentication.vtj-kysely.truststore.password: ${ssm_truststore_password}
authentication.vtj-kysely.cert-alias: "vtj-service"