server:
  servlet:
    context-path: /henkilo-ui
management:
  health:
    diskspace:
      enabled: false
henkiloui:
  lokalisointi_synkronointi:
    aktiivinen: false
  palvelukayttajat:
    lokalisointi:
      kayttajatunnus: henkiloui2lokalisointi
      salasana: henkiloui2lokalisointi
