server:
  servlet:
    context-path: /henkilo-ui
henkiloui:
  lokalisointi_synkronointi:
    aktiivinen: false
  palvelukayttajat:
    lokalisointi:
      kayttajatunnus: henkiloui2lokalisointi
      salasana: henkiloui2lokalisointi
