server:
  servlet:
    context-path: /henkilo-ui
management:
  health:
    diskspace:
      enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
henkiloui:
  lokalisointi_synkronointi:
    aktiivinen: false
  palvelukayttajat:
    lokalisointi:
      kayttajatunnus: henkiloui2lokalisointi
      salasana: henkiloui2lokalisointi
