//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fi.vm.sade.oppijanumerorekisteri.vtjkysely.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fi.vm.sade.oppijanumerorekisteri.vtjkysely.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fi.vm.sade.oppijanumerorekisteri.vtjkysely.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma }
     */
    public VTJHenkiloVastaussanoma createVTJHenkiloVastaussanoma() {
        return new VTJHenkiloVastaussanoma();
    }

    /**
     * Create an instance of {@link HaeTuotteenSkeemaResponse }
     * 
     * @return
     *     the new instance of {@link HaeTuotteenSkeemaResponse }
     */
    public HaeTuotteenSkeemaResponse createHaeTuotteenSkeemaResponse() {
        return new HaeTuotteenSkeemaResponse();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnusKyselyResponse }
     */
    public TeeHenkilonTunnusKyselyResponse createTeeHenkilonTunnusKyselyResponse() {
        return new TeeHenkilonTunnusKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnistusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnistusKyselyResponse }
     */
    public TeeHenkilonTunnistusKyselyResponse createTeeHenkilonTunnistusKyselyResponse() {
        return new TeeHenkilonTunnistusKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeHenkilonPoimintaKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonPoimintaKyselyResponse }
     */
    public TeeHenkilonPoimintaKyselyResponse createTeeHenkilonPoimintaKyselyResponse() {
        return new TeeHenkilonPoimintaKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeRakennusTunnusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeRakennusTunnusKyselyResponse }
     */
    public TeeRakennusTunnusKyselyResponse createTeeRakennusTunnusKyselyResponse() {
        return new TeeRakennusTunnusKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeRakennuksenTunnistusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeRakennuksenTunnistusKyselyResponse }
     */
    public TeeRakennuksenTunnistusKyselyResponse createTeeRakennuksenTunnistusKyselyResponse() {
        return new TeeRakennuksenTunnistusKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeKiinteistoTunnusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistoTunnusKyselyResponse }
     */
    public TeeKiinteistoTunnusKyselyResponse createTeeKiinteistoTunnusKyselyResponse() {
        return new TeeKiinteistoTunnusKyselyResponse();
    }

    /**
     * Create an instance of {@link TeeKiinteistonTunnistusKyselyResponse }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistonTunnistusKyselyResponse }
     */
    public TeeKiinteistonTunnistusKyselyResponse createTeeKiinteistonTunnistusKyselyResponse() {
        return new TeeKiinteistonTunnistusKyselyResponse();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo }
     */
    public VTJHenkiloVastaussanoma.Henkilo createVTJHenkiloVastaussanomaHenkilo() {
        return new VTJHenkiloVastaussanoma.Henkilo();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta createVTJHenkiloVastaussanomaHenkiloEdunvalvonta() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja createVTJHenkiloVastaussanomaHenkiloEdunvalvontaHenkiloEdunvalvoja() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus createVTJHenkiloVastaussanomaHenkiloEdunvalvontavaltuutus() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu createVTJHenkiloVastaussanomaHenkiloEdunvalvontavaltuutusHenkiloEdunvalvontavaltuutettu() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja createVTJHenkiloVastaussanomaHenkiloHuoltaja() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet }
     */
    public VTJHenkiloVastaussanoma.Hakuperusteet createVTJHenkiloVastaussanomaHakuperusteet() {
        return new VTJHenkiloVastaussanoma.Hakuperusteet();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Asiakasinfo }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Asiakasinfo }
     */
    public VTJHenkiloVastaussanoma.Asiakasinfo createVTJHenkiloVastaussanomaAsiakasinfo() {
        return new VTJHenkiloVastaussanoma.Asiakasinfo();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Paluukoodi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Paluukoodi }
     */
    public VTJHenkiloVastaussanoma.Paluukoodi createVTJHenkiloVastaussanomaPaluukoodi() {
        return new VTJHenkiloVastaussanoma.Paluukoodi();
    }

    /**
     * Create an instance of {@link HaeTuotteenSkeema }
     * 
     * @return
     *     the new instance of {@link HaeTuotteenSkeema }
     */
    public HaeTuotteenSkeema createHaeTuotteenSkeema() {
        return new HaeTuotteenSkeema();
    }

    /**
     * Create an instance of {@link HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult }
     * 
     * @return
     *     the new instance of {@link HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult }
     */
    public HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult createHaeTuotteenSkeemaResponseHaeTuotteenSkeemaResult() {
        return new HaeTuotteenSkeemaResponse.HaeTuotteenSkeemaResult();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnusKysely }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnusKysely }
     */
    public TeeHenkilonTunnusKysely createTeeHenkilonTunnusKysely() {
        return new TeeHenkilonTunnusKysely();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult }
     */
    public TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult createTeeHenkilonTunnusKyselyResponseTeeHenkilonTunnusKyselyResult() {
        return new TeeHenkilonTunnusKyselyResponse.TeeHenkilonTunnusKyselyResult();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnistusKysely }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnistusKysely }
     */
    public TeeHenkilonTunnistusKysely createTeeHenkilonTunnistusKysely() {
        return new TeeHenkilonTunnistusKysely();
    }

    /**
     * Create an instance of {@link TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult }
     */
    public TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult createTeeHenkilonTunnistusKyselyResponseTeeHenkilonTunnistusKyselyResult() {
        return new TeeHenkilonTunnistusKyselyResponse.TeeHenkilonTunnistusKyselyResult();
    }

    /**
     * Create an instance of {@link TeeHenkilonPoimintaKysely }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonPoimintaKysely }
     */
    public TeeHenkilonPoimintaKysely createTeeHenkilonPoimintaKysely() {
        return new TeeHenkilonPoimintaKysely();
    }

    /**
     * Create an instance of {@link TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult }
     */
    public TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult createTeeHenkilonPoimintaKyselyResponseTeeHenkilonPoimintaKyselyResult() {
        return new TeeHenkilonPoimintaKyselyResponse.TeeHenkilonPoimintaKyselyResult();
    }

    /**
     * Create an instance of {@link TeeRakennusTunnusKysely }
     * 
     * @return
     *     the new instance of {@link TeeRakennusTunnusKysely }
     */
    public TeeRakennusTunnusKysely createTeeRakennusTunnusKysely() {
        return new TeeRakennusTunnusKysely();
    }

    /**
     * Create an instance of {@link TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult }
     */
    public TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult createTeeRakennusTunnusKyselyResponseTeeRakennusTunnusKyselyResult() {
        return new TeeRakennusTunnusKyselyResponse.TeeRakennusTunnusKyselyResult();
    }

    /**
     * Create an instance of {@link TeeRakennuksenTunnistusKysely }
     * 
     * @return
     *     the new instance of {@link TeeRakennuksenTunnistusKysely }
     */
    public TeeRakennuksenTunnistusKysely createTeeRakennuksenTunnistusKysely() {
        return new TeeRakennuksenTunnistusKysely();
    }

    /**
     * Create an instance of {@link TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult }
     */
    public TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult createTeeRakennuksenTunnistusKyselyResponseTeeRakennuksenTunnistusKyselyResult() {
        return new TeeRakennuksenTunnistusKyselyResponse.TeeRakennuksenTunnistusKyselyResult();
    }

    /**
     * Create an instance of {@link TeeKiinteistoTunnusKysely }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistoTunnusKysely }
     */
    public TeeKiinteistoTunnusKysely createTeeKiinteistoTunnusKysely() {
        return new TeeKiinteistoTunnusKysely();
    }

    /**
     * Create an instance of {@link TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult }
     */
    public TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult createTeeKiinteistoTunnusKyselyResponseTeeKiinteistoTunnusKyselyResult() {
        return new TeeKiinteistoTunnusKyselyResponse.TeeKiinteistoTunnusKyselyResult();
    }

    /**
     * Create an instance of {@link TeeKiinteistonTunnistusKysely }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistonTunnistusKysely }
     */
    public TeeKiinteistonTunnistusKysely createTeeKiinteistonTunnistusKysely() {
        return new TeeKiinteistonTunnistusKysely();
    }

    /**
     * Create an instance of {@link TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult }
     * 
     * @return
     *     the new instance of {@link TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult }
     */
    public TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult createTeeKiinteistonTunnistusKyselyResponseTeeKiinteistonTunnistusKyselyResult() {
        return new TeeKiinteistonTunnistusKyselyResponse.TeeKiinteistonTunnistusKyselyResult();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Henkilotunnus }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Henkilotunnus }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Henkilotunnus createVTJHenkiloVastaussanomaHenkiloHenkilotunnus() {
        return new VTJHenkiloVastaussanoma.Henkilo.Henkilotunnus();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Sukupuoli }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Sukupuoli }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Sukupuoli createVTJHenkiloVastaussanomaHenkiloSukupuoli() {
        return new VTJHenkiloVastaussanoma.Henkilo.Sukupuoli();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Aidinkieli }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Aidinkieli }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Aidinkieli createVTJHenkiloVastaussanomaHenkiloAidinkieli() {
        return new VTJHenkiloVastaussanoma.Henkilo.Aidinkieli();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kuolintiedot }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kuolintiedot }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Kuolintiedot createVTJHenkiloVastaussanomaHenkiloKuolintiedot() {
        return new VTJHenkiloVastaussanoma.Henkilo.Kuolintiedot();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyinenSukunimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyinenSukunimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.NykyinenSukunimi createVTJHenkiloVastaussanomaHenkiloNykyinenSukunimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.NykyinenSukunimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyisetEtunimet }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyisetEtunimet }
     */
    public VTJHenkiloVastaussanoma.Henkilo.NykyisetEtunimet createVTJHenkiloVastaussanomaHenkiloNykyisetEtunimet() {
        return new VTJHenkiloVastaussanoma.Henkilo.NykyisetEtunimet();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyinenKutsumanimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.NykyinenKutsumanimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.NykyinenKutsumanimi createVTJHenkiloVastaussanomaHenkiloNykyinenKutsumanimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.NykyinenKutsumanimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.EntinenNimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.EntinenNimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.EntinenNimi createVTJHenkiloVastaussanomaHenkiloEntinenNimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.EntinenNimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.VakinainenKotimainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.VakinainenKotimainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.VakinainenKotimainenOsoite createVTJHenkiloVastaussanomaHenkiloVakinainenKotimainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.VakinainenKotimainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.VakinainenUlkomainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.VakinainenUlkomainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.VakinainenUlkomainenOsoite createVTJHenkiloVastaussanomaHenkiloVakinainenUlkomainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.VakinainenUlkomainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.TilapainenKotimainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.TilapainenKotimainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.TilapainenKotimainenOsoite createVTJHenkiloVastaussanomaHenkiloTilapainenKotimainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.TilapainenKotimainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.TilapainenUlkomainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.TilapainenUlkomainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.TilapainenUlkomainenOsoite createVTJHenkiloVastaussanomaHenkiloTilapainenUlkomainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.TilapainenUlkomainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.KotimainenPostiosoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.KotimainenPostiosoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.KotimainenPostiosoite createVTJHenkiloVastaussanomaHenkiloKotimainenPostiosoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.KotimainenPostiosoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenPostiosoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenPostiosoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.UlkomainenPostiosoite createVTJHenkiloVastaussanomaHenkiloUlkomainenPostiosoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.UlkomainenPostiosoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kotikunta }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kotikunta }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Kotikunta createVTJHenkiloVastaussanomaHenkiloKotikunta() {
        return new VTJHenkiloVastaussanoma.Henkilo.Kotikunta();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Turvakielto }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Turvakielto }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Turvakielto createVTJHenkiloVastaussanomaHenkiloTurvakielto() {
        return new VTJHenkiloVastaussanoma.Henkilo.Turvakielto();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Ammatti }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Ammatti }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Ammatti createVTJHenkiloVastaussanomaHenkiloAmmatti() {
        return new VTJHenkiloVastaussanoma.Henkilo.Ammatti();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenHenkilonumero }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenHenkilonumero }
     */
    public VTJHenkiloVastaussanoma.Henkilo.UlkomainenHenkilonumero createVTJHenkiloVastaussanomaHenkiloUlkomainenHenkilonumero() {
        return new VTJHenkiloVastaussanoma.Henkilo.UlkomainenHenkilonumero();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kansalaisuus }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Kansalaisuus }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Kansalaisuus createVTJHenkiloVastaussanomaHenkiloKansalaisuus() {
        return new VTJHenkiloVastaussanoma.Henkilo.Kansalaisuus();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenSyntymapaikka }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.UlkomainenSyntymapaikka }
     */
    public VTJHenkiloVastaussanoma.Henkilo.UlkomainenSyntymapaikka createVTJHenkiloVastaussanomaHenkiloUlkomainenSyntymapaikka() {
        return new VTJHenkiloVastaussanoma.Henkilo.UlkomainenSyntymapaikka();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huollettava }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huollettava }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huollettava createVTJHenkiloVastaussanomaHenkiloHuollettava() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huollettava();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.YritysJaYhteisoEdunvalvoja }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.YritysJaYhteisoEdunvalvoja }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.YritysJaYhteisoEdunvalvoja createVTJHenkiloVastaussanomaHenkiloEdunvalvontaYritysJaYhteisoEdunvalvoja() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.YritysJaYhteisoEdunvalvoja();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.OikeusaputoimistoEdunvalvoja }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.OikeusaputoimistoEdunvalvoja }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.OikeusaputoimistoEdunvalvoja createVTJHenkiloVastaussanomaHenkiloEdunvalvontaOikeusaputoimistoEdunvalvoja() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.OikeusaputoimistoEdunvalvoja();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyinenSukunimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyinenSukunimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyinenSukunimi createVTJHenkiloVastaussanomaHenkiloEdunvalvontaHenkiloEdunvalvojaNykyinenSukunimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyinenSukunimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyisetEtunimet }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyisetEtunimet }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyisetEtunimet createVTJHenkiloVastaussanomaHenkiloEdunvalvontaHenkiloEdunvalvojaNykyisetEtunimet() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvonta.HenkiloEdunvalvoja.NykyisetEtunimet();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyinenSukunimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyinenSukunimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyinenSukunimi createVTJHenkiloVastaussanomaHenkiloEdunvalvontavaltuutusHenkiloEdunvalvontavaltuutettuNykyinenSukunimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyinenSukunimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyisetEtunimet }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyisetEtunimet }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyisetEtunimet createVTJHenkiloVastaussanomaHenkiloEdunvalvontavaltuutusHenkiloEdunvalvontavaltuutettuNykyisetEtunimet() {
        return new VTJHenkiloVastaussanoma.Henkilo.Edunvalvontavaltuutus.HenkiloEdunvalvontavaltuutettu.NykyisetEtunimet();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.Huoltotiedot }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.Huoltotiedot }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja.Huoltotiedot createVTJHenkiloVastaussanomaHenkiloHuoltajaHuoltotiedot() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja.Huoltotiedot();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyinenSukunimi }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyinenSukunimi }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyinenSukunimi createVTJHenkiloVastaussanomaHenkiloHuoltajaNykyinenSukunimi() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyinenSukunimi();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyisetEtunimet }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyisetEtunimet }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyisetEtunimet createVTJHenkiloVastaussanomaHenkiloHuoltajaNykyisetEtunimet() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja.NykyisetEtunimet();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenKotimainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenKotimainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenKotimainenOsoite createVTJHenkiloVastaussanomaHenkiloHuoltajaVakinainenKotimainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenKotimainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenUlkomainenOsoite }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenUlkomainenOsoite }
     */
    public VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenUlkomainenOsoite createVTJHenkiloVastaussanomaHenkiloHuoltajaVakinainenUlkomainenOsoite() {
        return new VTJHenkiloVastaussanoma.Henkilo.Huoltaja.VakinainenUlkomainenOsoite();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet.Henkilotunnus }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet.Henkilotunnus }
     */
    public VTJHenkiloVastaussanoma.Hakuperusteet.Henkilotunnus createVTJHenkiloVastaussanomaHakuperusteetHenkilotunnus() {
        return new VTJHenkiloVastaussanoma.Hakuperusteet.Henkilotunnus();
    }

    /**
     * Create an instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet.SahkoinenAsiointitunnus }
     * 
     * @return
     *     the new instance of {@link VTJHenkiloVastaussanoma.Hakuperusteet.SahkoinenAsiointitunnus }
     */
    public VTJHenkiloVastaussanoma.Hakuperusteet.SahkoinenAsiointitunnus createVTJHenkiloVastaussanomaHakuperusteetSahkoinenAsiointitunnus() {
        return new VTJHenkiloVastaussanoma.Hakuperusteet.SahkoinenAsiointitunnus();
    }

}
