import { Asiointikieli } from '../kayttooikeus/Kutsu.types';

export type OrganisaatioStatus = 'AKTIIVINEN' | 'SUUNNITELTU' | 'PASSIIVINEN' | 'POISTETTU';

export type Organisaatio = {
    oid: string;
    parentOidPath: string;
    nimi: {
        fi?: string;
        sv?: string;
        en?: string;
    };
    tyypit: string[];
    status: OrganisaatioStatus;
};

export type OrganisaatioWithChildren = {
    oid: string;
    parentOidPath: string;
    nimi: {
        fi?: string;
        sv?: string;
        en?: string;
    };
    tyypit: string[];
    children: OrganisaatioWithChildren[];
    status: OrganisaatioStatus;

    // generated by ui
    parentOid: string | null | undefined;
    parent: OrganisaatioWithChildren;
};

export type OrganisaatioNameLookup = Record<string, Record<Asiointikieli, string>>;
