export type OrganisaatioStatus = 'AKTIIVINEN' | 'SUUNNITELTU' | 'PASSIIVINEN' | 'POISTETTU';

export type Organisaatio = {
    oid: string;
    parentOidPath: string;
    nimi: {
        fi?: string;
        sv?: string;
        en?: string;
    };
    tyypit: Array<string>;
    status: OrganisaatioStatus;
};

export type OrganisaatioWithChildren = {
    oid: string;
    parentOidPath: string;
    nimi: {
        fi?: string;
        sv?: string;
        en?: string;
    };
    tyypit: Array<string>;
    children: Array<OrganisaatioWithChildren>;
    status: OrganisaatioStatus;

    // generated by ui
    parentOid: string | null | undefined;
    parent: OrganisaatioWithChildren;
};

export type OrganisaatioTyyppi = 'ORGANISAATIO' | 'RYHMA';

export type OrganisaatioCriteria = {
    tyyppi?: OrganisaatioTyyppi;
    tila?: Array<OrganisaatioStatus>;
};
