export const FETCH_LOCALISATIONS_SUCCESS = 'FETCH_LOCALISATIONS_SUCCESS';

export const FETCH_HENKILO_REQUEST = 'FETCH_HENKILO_REQUEST';
export const FETCH_HENKILO_SUCCESS = 'FETCH_HENKILO_SUCCESS';
export const FETCH_HENKILO_FAILURE = 'FETCH_HENKILO_FAILURE';

export const UPDATE_HENKILO_REQUEST = 'UPDATE_HENKILO_REQUEST';
export const UPDATE_HENKILO_FAILURE = 'UPDATE_HENKILO_FAILURE';

export const FETCH_PREQUEL_REQUEST = 'FETCH_PREQUEL_REQUEST';
export const FETCH_PREQUEL_SUCCESS = 'FETCH_PREQUEL_SUCCESS';
export const FETCH_PREQUEL_FAILURE = 'FETCH_PREQUEL_FAILURE';

export const FETCH_HENKILO_ASIOINTIKIELI_SUCCESS = 'FETCH_HENKILO_ASIOINTIKIELI_SUCCESS';

export const GLOBAL_NOTIFICATION = {
    ADD: 'ADD_GLOBAL_NOTIFICATION',
    REMOVE: 'REMOVE_GLOBAL_NOTIFICATION',
};

export const CLEAR_HENKILO = 'CLEAR_HENKILO';
