export const FETCH_HENKILO_REQUEST = 'FETCH_HENKILO_REQUEST';
export const FETCH_HENKILO_SUCCESS = 'FETCH_HENKILO_SUCCESS';
export const FETCH_HENKILO_FAILURE = 'FETCH_HENKILO_FAILURE';

export const GLOBAL_NOTIFICATION = {
    ADD: 'ADD_GLOBAL_NOTIFICATION',
    REMOVE: 'REMOVE_GLOBAL_NOTIFICATION',
};

export const CLEAR_HENKILO = 'CLEAR_HENKILO';
