export const FETCH_LOCALISATIONS_SUCCESS = 'FETCH_LOCALISATIONS_SUCCESS';

export const FETCH_HENKILO_REQUEST = 'FETCH_HENKILO_REQUEST';
export const FETCH_HENKILO_SUCCESS = 'FETCH_HENKILO_SUCCESS';
export const FETCH_HENKILO_FAILURE = 'FETCH_HENKILO_FAILURE';

export const FETCH_KAYTTAJA_REQUEST = 'FETCH_KAYTTAJA_REQUEST';
export const FETCH_KAYTTAJA_SUCCESS = 'FETCH_KAYTTAJA_SUCCESS';
export const FETCH_KAYTTAJA_FAILURE = 'FETCH_KAYTTAJA_FAILURE';

export const FETCH_KAYTTAJATIETO_REQUEST = 'FETCH_KAYTTAJATIETO_REQUEST';
export const FETCH_KAYTTAJATIETO_SUCCESS = 'FETCH_KAYTTAJATIETO_SUCCESS';
export const FETCH_KAYTTAJATIETO_FAILURE = 'FETCH_KAYTTAJATIETO_FAILURE';

export const UPDATE_KAYTTAJATIETO_REQUEST = 'UPDATE_KAYTTAJATIETO_REQUEST';
export const UPDATE_KAYTTAJATIETO_SUCCESS = 'UPDATE_KAYTTAJATIETO_SUCCESS';
export const UPDATE_KAYTTAJATIETO_FAILURE = 'UPDATE_KAYTTAJATIETO_FAILURE';

export const PASSIVOI_HENKILO_FAILURE = 'PASSIVOI_HENKILO_FAILURE';

export const YKSILOI_HENKILO_FAILURE = 'YKSILOI_HENKILO_FAILURE';
export const YKSILOI_PUUTTUVAT_TIEDOT_FAILURE = 'YKSILOI_PUUTTUVAT_TIEDOT_FAILURE';

export const VTJ_OVERRIDE_YKSILOIMATON_HENKILO_REQUEST = 'VTJ_OVERRIDE_YKSILOIMATON_HENKILO_REQUEST';
export const VTJ_OVERRIDE_YKSILOIMATON_HENKILO_SUCCESS = 'VTJ_OVERRIDE_YKSILOIMATON_HENKILO_SUCCESS';
export const VTJ_OVERRIDE_YKSILOIMATON_HENKILO_FAILURE = 'VTJ_OVERRIDE_YKSILOIMATON_HENKILO_FAILURE';

export const UPDATE_HENKILO_REQUEST = 'UPDATE_HENKILO_REQUEST';
export const UPDATE_HENKILO_FAILURE = 'UPDATE_HENKILO_FAILURE';

export const FETCH_PREQUEL_REQUEST = 'FETCH_PREQUEL_REQUEST';
export const FETCH_PREQUEL_SUCCESS = 'FETCH_PREQUEL_SUCCESS';
export const FETCH_PREQUEL_FAILURE = 'FETCH_PREQUEL_FAILURE';

export const FETCH_OMATTIEDOT_SUCCESS = 'FETCH_OMATTIEDOT_SUCCESS';

export const FETCH_OMATTIEDOT_ORGANISAATIOS_SUCCESS = 'FETCH_OMATTIEDOT_ORGANISAATIOS_SUCCESS';

export const FETCH_HENKILO_ASIOINTIKIELI_SUCCESS = 'FETCH_HENKILO_ASIOINTIKIELI_SUCCESS';

export const GLOBAL_NOTIFICATION = {
    ADD: 'ADD_GLOBAL_NOTIFICATION',
    REMOVE: 'REMOVE_GLOBAL_NOTIFICATION',
};

export const CLEAR_HENKILO = 'CLEAR_HENKILO';

export const FETCH_HENKILO_HAKEMUKSET = {
    REQUEST: 'FETCH_HENKILO_HAKEMUKSET_REQUEST',
    SUCCESS: 'FETCH_HENKILO_HAKEMUKSET_SUCCESS',
    FAILURE: 'FETCH_HENKILO_HAKEMUKSET_FAILURE',
};
