server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5436/tiedotuspalvelu
spring.datasource.username=tiedotuspalvelu
spring.datasource.password=tiedotuspalvelu

tiedotuspalvelu.oppija-origin=http://localhost:8086
tiedotuspalvelu.virkailija-origin=http://localhost:8087
tiedotuspalvelu.api-base-url=http://localhost:8086
tiedotuspalvelu.opintopolku-host=testiopintopolku.fi
tiedotuspalvelu.fetch-localisations.enabled=false

# OAuth2 client credentials
tiedotuspalvelu.otuva.oauth2-client-id=tiedotuspalvelu
tiedotuspalvelu.otuva.oauth2-client-secret=tiedotuspalvelu

# Otuva cas fakes
tiedotuspalvelu.cas-oppija.server-url=http://localhost:8888/realms/cas-oppija/protocol/cas
tiedotuspalvelu.cas-virkailija.server-url=http://localhost:8888/realms/cas-virkailija/protocol/cas
# Otuva OAuth2 fake
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8888/realms/otuva-oauth2/protocol/openid-connect/certs
tiedotuspalvelu.otuva.oauth2-token-url=http://localhost:8888/realms/otuva-oauth2/protocol/openid-connect/token
tiedotuspalvelu.swagger-ui.oauth2-token-url=http://localhost:8888/realms/otuva-oauth2/protocol/openid-connect/token

# Prefill Swagger UI OAuth2 dialog
springdoc.swagger-ui.oauth.client-id=kielitutkinnosta-tiedottaja
springdoc.swagger-ui.oauth.client-secret=kielitutkinnosta-tiedottaja
