git:
  depth: false
branches:
  only:
    - master
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "Nbx6ARVe/lsd1G+IT8Fsr78vEnHlo5iE8lGYP3IzsRXzhvqdA22Vk549DdiOOIiN5Vxn7uuKA60SCUqopY9Oycmk+MXgGTj5jKoivy+e6ar89QTPELGzgO2DbUtYekWCrwJ/QpEDYu1JQGte4owoE/WnvCWmV6oPHL3d7HvgKAzHOQRd09wLDN/fgRZn/rjpPgLqkDiAgkSud5oPkKyha1GyylyWvoB1aMqdeHg0ConAcPq57s8qOwcZ7lXN5RRa8H7FUqskd2kWESw6ZbYLwGC8hKiqnJiByUbJ7PFIg+9eOwtmamm2F6O7W4lzBQ7Iarthf4X7oszR5rFllF2Q79ZqqZrpNqvjCjK/C2m3MLth/MeCAjZQy2Nmsa/TNGxHhQzswvrWEKNCDSi5PynSj38W6NafvFNquI9XnWtx2y/7YY3sjmSj5VRcNqdCdaIs+c98GZrBv6dmYvPAfDjQyw9RUd45tKd8cEYemAiVS05RhxC5YxL+ZJuAjER0iejvlDxyEBIA93hNCxytCYKO1B0lDI7naFv1GpqT2p8Bdzfhxw87ZZrzkdSQz5ZxTBjOXb7+niKMMruRgZ7WmHJsAysUt45DIAkNBuH+ZUedqhOEeUs9+LxeHG5iUnoHSgqA9VxTO99l+Ecc5sC81FrU8J2QsPKg1KhnU//foIckoAw="
    # AWS_SECRET_ACCESS_KEY
    - secure: "dl6NApkYGbzpDnUmRykeBziB7uO12ZJ/z1ToT1YF9v+iwXY4A5NigQJ67A4AmtqhDJejj67/3pbwWeqk2VW4Xt2+XkEPZrwnEuJLB3Z9Ul3mmrgKlulC75wRbB/yZ8BfHl58DL85hF9oLl3WgOYTgMYhtK4q9np/hiUzi4+DW7teHJnTVYSCphwfavGxUNCMVzwVCBUiq64Wj8DrbSRgp/1VNUyHcmei2HFKmW8poonm3bqMT9ICAhPl/c00YFQ0HnG2BxrWooW/CXK6cRXAbS+JdUQF0ylT3RlZk5JWw3Qsw7IKOmuTLZFOOxblSX9xMtucW27RoNkQdM9culbtlscloJ0jggPvC7MF5TbxBZuW9jI0UqfbZNHieR0xVMRWWuaVDqlA4HolQvCnWlA6x10yuZZtBiJDBxgen72pJo0TZaRl8EBHaCY/FuA/9j2uEDU0hht8n4loHGd/pbMwfEmgq6k2d00+UG+/GLherggrZYDDiJWBz7HH8ffwgfOfjNSp3Dx4QxgTxjg/ubYz3VvY9LuMzNda4Sm7ZPTwXTYL353zAu4gofWUWQ+dMWo5tfSC1Le4YQyiYe2Qbi6azydy/mLW7yxVURsltR3DwYSR76TbTmH7IIBSpx1avbX9GzCUo2/OcrSoB6aIQB/a+cWwoeJZjlXIbPNdQi67aZQ="

addons:
  sonarcloud:
    organization: "opetushallitus"
    token:
      secure: "BtE/SP2vhEgNAE9Im3Dg/9Qe1Ueb6fFIHAD+vt2IrKxwmFUd47ObRFXgPhrZzSZIB+Q29bO1+5Igcb/mmVmpkBi6TjX12azh0rjL1QBZenmEAl5J65sQat9Ip1lXhrBpfTt4w8HEN8l6gs8hZB9+uKTz7waCDJwxNa5vU9nRt8hB+5IDJBRM0UZrG3St+mlHSMotEpwmEQ8kDaoNwt0wRQtu7Afck03ydZOZdX3cskT6TPQv+Z3C7Wk/US/RyDa95WHx7PnG4ywwSZimUi4y38gC0GNSb+39rdUfrs3v/Fb+upS0LpK7yAtYbS+wI5bbaQJKkzoReeWmHuR/+Md6OCt2JgsXJDLQF3MmUKVHK3k0QF6rwOS1vuqRQYl3R8490dogBAVvi0ov/uK1pOFJzAsmu8L4wnqOHqoocmL+0vRSXOOv/KnXGiIC9GEIFrKmoU1AMm0OF2KMMqdaqzFYTkrqwM9J54qEKlsdhxRq2Zxp8W+Ptvg9m+3is2AUxqYjBBiSMnqWhUxfp5+xQcKAZ3rjSS7GMwPoGqph3Ui/U4CzYT6Xj8PhSwIWT2yqSh318OW3N51AOcfQCMuoI3Fit5SCdJZ5YOc22Wq7bec7fZRSFytGr8pwtPHAK+1UpQ8MhzpuJ5YcWnGNFy6vhkNbGOLxNqs1J4Z/MPF+nOu5iVg="

before_install:
  - nvm install 12.18.1
  - nvm use 12.18.1

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="henkilo-ui"

script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=Opetushallitus_henkilo-ui -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv target/henkiloui-*.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME
  - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
